<?php
//French state list
//using iso 3166-2:fr codes
function getOptions_fr()
{

$options[] = array('id' =>'-', 'name'=>xarML('--METROPOLITAN REGIONS--'));
$options[] = array('id' =>'FR-A', 'name'=>xarML('Alsace'));
$options[] = array('id' =>'FR-B', 'name'=>xarML('Aquitaine'));
$options[] = array('id' =>'FR-C', 'name'=>xarML('Auvergne'));
$options[] = array('id' =>'FR-P', 'name'=>xarML('Basse-Normandie'));
$options[] = array('id' =>'FR-D', 'name'=>xarML('Bourgogne'));
$options[] = array('id' =>'FR-E', 'name'=>xarML('Bretagne'));
$options[] = array('id' =>'FR-F', 'name'=>xarML('Centre'));
$options[] = array('id' =>'FR-G', 'name'=>xarML('Champagne-Ardenne'));
$options[] = array('id' =>'FR-H', 'name'=>xarML('Corse'));
$options[] = array('id' =>'FR-I', 'name'=>xarML('Franche-Comté'));
$options[] = array('id' =>'FR-Q', 'name'=>xarML('Haute-Normandie'));
$options[] = array('id' =>'FR-J', 'name'=>xarML('Ile-de-France'));
$options[] = array('id' =>'FR-K', 'name'=>xarML('Languedoc-Roussillon'));
$options[] = array('id' =>'FR-L', 'name'=>xarML('Limousin'));
$options[] = array('id' =>'FR-M', 'name'=>xarML('Lorraine'));
$options[] = array('id' =>'FR-N', 'name'=>xarML('Midi-Pyrénées'));
$options[] = array('id' =>'FR-O', 'name'=>xarML('Nord-Pas-de-Calais'));
$options[] = array('id' =>'FR-R', 'name'=>xarML('Pays de la Loire'));
$options[] = array('id' =>'FR-S', 'name'=>xarML('Picardie'));
$options[] = array('id' =>'FR-T', 'name'=>xarML('Poitou-Charentes'));
$options[] = array('id' =>'FR-U', 'name'=>xarML('Provence-Alpes-Côte d\'Azur'));
$options[] = array('id' =>'FR-V', 'name'=>xarML('Rhône-Alpes'));
$options[] = array('id' =>'--',   'name'=>xarML('--OVERSEAS REGIONS/DEPT--'));
$options[] = array('id' =>'FR-GP','name'=>xarML('Guadeloupe'));
$options[] = array('id' =>'FR-GF','name'=>xarML('Guyane (française)'));
$options[] = array('id' =>'FR-MQ','name'=>xarML('Martinique'));
$options[] = array('id' =>'FR-RE','name'=>xarML('La Réunion'));
$options[] = array('id' =>'---',  'name'=>xarML('--METROPOLITAN DEPARTMENTS--'));
$options[] = array('id' =>'FR-01', 'name'=>xarML('Ain'));
$options[] = array('id' =>'FR-02', 'name'=>xarML('Aisne'));
$options[] = array('id' =>'FR-03', 'name'=>xarML('Allier'));
$options[] = array('id' =>'FR-04', 'name'=>xarML('Alpes-de-Haute-Provence'));
$options[] = array('id' =>'FR-06', 'name'=>xarML('Alpes-Maritimes'));
$options[] = array('id' =>'FR-07', 'name'=>xarML('Ardèche'));
$options[] = array('id' =>'FR-08', 'name'=>xarML('Ardennes'));
$options[] = array('id' =>'FR-09', 'name'=>xarML('Ariège'));
$options[] = array('id' =>'FR-10', 'name'=>xarML('Aube'));
$options[] = array('id' =>'FR-11', 'name'=>xarML('Aude'));
$options[] = array('id' =>'FR-12', 'name'=>xarML('Aveyron'));
$options[] = array('id' =>'FR-67', 'name'=>xarML('Bas-Rhin'));
$options[] = array('id' =>'FR-13', 'name'=>xarML('Bouches-du-Rhône'));
$options[] = array('id' =>'FR-14', 'name'=>xarML('Calvados'));
$options[] = array('id' =>'FR-15', 'name'=>xarML('Cantal'));
$options[] = array('id' =>'FR-16', 'name'=>xarML('Charente'));
$options[] = array('id' =>'FR-17', 'name'=>xarML('Charente-Maritime'));
$options[] = array('id' =>'FR-18', 'name'=>xarML('Cher'));
$options[] = array('id' =>'FR-19', 'name'=>xarML('Corrèze'));
$options[] = array('id' =>'FR-2A', 'name'=>xarML('Corse-du-Sud'));
$options[] = array('id' =>'FR-21', 'name'=>xarML('Cote-d\'Or'));
$options[] = array('id' =>'FR-22', 'name'=>xarML('Cotes-d\'Armor'));
$options[] = array('id' =>'FR-23', 'name'=>xarML('Creuse'));
$options[] = array('id' =>'FR-79', 'name'=>xarML('Deux-Sèvres'));
$options[] = array('id' =>'FR-24', 'name'=>xarML('Dordogne'));
$options[] = array('id' =>'FR-25', 'name'=>xarML('Doubs'));
$options[] = array('id' =>'FR-26', 'name'=>xarML('Drôme'));
$options[] = array('id' =>'FR-91', 'name'=>xarML('Essonne'));
$options[] = array('id' =>'FR-27', 'name'=>xarML('Eure'));
$options[] = array('id' =>'FR-28', 'name'=>xarML('Eure-et-Loir'));
$options[] = array('id' =>'FR-29', 'name'=>xarML('Finistère'));
$options[] = array('id' =>'FR-30', 'name'=>xarML('Gard'));
$options[] = array('id' =>'FR-32', 'name'=>xarML('Gers'));
$options[] = array('id' =>'FR-33', 'name'=>xarML('Gironde'));
$options[] = array('id' =>'FR-2B', 'name'=>xarML('Haute-Corse'));
$options[] = array('id' =>'FR-31', 'name'=>xarML('Haute-Garonne'));
$options[] = array('id' =>'FR-43', 'name'=>xarML('Haute-Loire'));
$options[] = array('id' =>'FR-52', 'name'=>xarML('Haute-Marne'));
$options[] = array('id' =>'FR-05', 'name'=>xarML('Hautes-Alpes'));
$options[] = array('id' =>'FR-70', 'name'=>xarML('Haute-Saône'));
$options[] = array('id' =>'FR-74', 'name'=>xarML('Haute-Savoie'));
$options[] = array('id' =>'FR-65', 'name'=>xarML('Hautes-Pyrénées'));
$options[] = array('id' =>'FR-87', 'name'=>xarML('Haute-Vienne'));
$options[] = array('id' =>'FR-68', 'name'=>xarML('Haut-Rhin'));
$options[] = array('id' =>'FR-92', 'name'=>xarML('Hauts-de-Seine'));
$options[] = array('id' =>'FR-34', 'name'=>xarML('Hérault'));
$options[] = array('id' =>'FR-35', 'name'=>xarML('Ille-et-Vilaine'));
$options[] = array('id' =>'FR-36', 'name'=>xarML('Indre'));
$options[] = array('id' =>'FR-37', 'name'=>xarML('Indre-et-Loire'));
$options[] = array('id' =>'FR-38', 'name'=>xarML('Isère'));
$options[] = array('id' =>'FR-39', 'name'=>xarML('Jura'));
$options[] = array('id' =>'FR-40', 'name'=>xarML('Landes'));
$options[] = array('id' =>'FR-42', 'name'=>xarML('Loire'));
$options[] = array('id' =>'FR-44', 'name'=>xarML('Loire-Atlantique'));
$options[] = array('id' =>'FR-45', 'name'=>xarML('Loiret'));
$options[] = array('id' =>'FR-41', 'name'=>xarML('Loiret-Cher'));
$options[] = array('id' =>'FR-46', 'name'=>xarML('Lot'));
$options[] = array('id' =>'FR-47', 'name'=>xarML('Lot-et-Garonne'));
$options[] = array('id' =>'FR-48', 'name'=>xarML('Lozère'));
$options[] = array('id' =>'FR-49', 'name'=>xarML('Maine-et-Loire'));
$options[] = array('id' =>'FR-50', 'name'=>xarML('Manche'));
$options[] = array('id' =>'FR-51', 'name'=>xarML('Marne'));
$options[] = array('id' =>'FR-53', 'name'=>xarML('Mayenne'));
$options[] = array('id' =>'FR-54', 'name'=>xarML('Meurthe-et-Moselle'));
$options[] = array('id' =>'FR-55', 'name'=>xarML('Meuse'));
$options[] = array('id' =>'FR-56', 'name'=>xarML('Morbihan'));
$options[] = array('id' =>'FR-57', 'name'=>xarML('Moselle'));
$options[] = array('id' =>'FR-58', 'name'=>xarML('Nièvre'));
$options[] = array('id' =>'FR-59', 'name'=>xarML('Nord'));
$options[] = array('id' =>'FR-60', 'name'=>xarML('Oise'));
$options[] = array('id' =>'FR-61', 'name'=>xarML('Orne'));
$options[] = array('id' =>'FR-75', 'name'=>xarML('Paris'));
$options[] = array('id' =>'FR-62', 'name'=>xarML('Pas-de-Calais'));
$options[] = array('id' =>'FR-63', 'name'=>xarML('Puy-de-Dôme'));
$options[] = array('id' =>'FR-64', 'name'=>xarML('Pyrénées-Atlantiques'));
$options[] = array('id' =>'FR-66', 'name'=>xarML('Pyrénées-Orientales'));
$options[] = array('id' =>'FR-69', 'name'=>xarML('Rhône'));
$options[] = array('id' =>'FR-71', 'name'=>xarML('Saône-et-Loire'));
$options[] = array('id' =>'FR-72', 'name'=>xarML('Sarthe'));
$options[] = array('id' =>'FR-73', 'name'=>xarML('Savoie'));
$options[] = array('id' =>'FR-77', 'name'=>xarML('Seine-et-Marne'));
$options[] = array('id' =>'FR-76', 'name'=>xarML('Seine-Maritime'));
$options[] = array('id' =>'FR-93', 'name'=>xarML('Seine-Saint-Denis'));
$options[] = array('id' =>'FR-80', 'name'=>xarML('Somme'));
$options[] = array('id' =>'FR-81', 'name'=>xarML('Tarn'));
$options[] = array('id' =>'FR-82', 'name'=>xarML('Tarn-et-Garonne'));
$options[] = array('id' =>'FR-90', 'name'=>xarML('Territoire de Belfort'));
$options[] = array('id' =>'FR-94', 'name'=>xarML('Val-de-Marne'));
$options[] = array('id' =>'FR-95', 'name'=>xarML('Val-d\'Oise'));
$options[] = array('id' =>'FR-83', 'name'=>xarML('Var'));
$options[] = array('id' =>'FR-84', 'name'=>xarML('Vaucluse'));
$options[] = array('id' =>'FR-85', 'name'=>xarML('Vendée'));
$options[] = array('id' =>'FR-86', 'name'=>xarML('Vienne'));
$options[] = array('id' =>'FR-88', 'name'=>xarML('Vosges'));
$options[] = array('id' =>'FR-89', 'name'=>xarML('Yonne'));
$options[] = array('id' =>'FR-78', 'name'=>xarML('Yvelines'));
$options[] = array('id' =>'----', 'name'=>xarML('--DEPENDENCY/TERRITORIAL COLLECTIVITIES--'));
$options[] = array('id' =>'FR-CP', 'name'=>xarML('Clipperton'));
$options[] = array('id' =>'FR-YT', 'name'=>xarML('Mayotte'));
$options[] = array('id' =>'FR-NC', 'name'=>xarML('Nouvelle-Calédonie'));
$options[] = array('id' =>'FR-PF', 'name'=>xarML('Polynésie française'));
$options[] = array('id' =>'FR-BL', 'name'=>xarML('Saint-Barthélemy'));
$options[] = array('id' =>'FR-MF', 'name'=>xarML('Saint-Martin'));
$options[] = array('id' =>'FR-PM', 'name'=>xarML('Saint-Pierre-et-Miquelon'));
$options[] = array('id' =>'FR-TF', 'name'=>xarML('Terres australes françaises'));
$options[] = array('id' =>'FR-WF', 'name'=>xarML('Wallis-et-Futuna'));

    return $options;
}
?>