<?php
//United kingdom burrough, district, county, province list
//using iso 3166-2:gb codes
function getOptions_gb()
{
$options[] = array('id' =>'-', 'name' =>'--ENG TWO TIER COUNTIES--');
$options[] = array('id' =>'GB-BKM', 'name' =>'Buckinghamshire');
$options[] = array('id' =>'GB-CAM', 'name' =>'Cambridgeshire');
$options[] = array('id' =>'GB-CMA', 'name' =>'Cumbria');
$options[] = array('id' =>'GB-DBY', 'name' =>'Derbyshire');
$options[] = array('id' =>'GB-DEV', 'name' =>'Devon');
$options[] = array('id' =>'GB-DOR', 'name' =>'Dorset');
$options[] = array('id' =>'GB-ESX', 'name' =>'East Sussex');
$options[] = array('id' =>'GB-ESS', 'name' =>'Essex');
$options[] = array('id' =>'GB-GLS', 'name' =>'Gloucestershire');
$options[] = array('id' =>'GB-HAM', 'name' =>'Hampshire');
$options[] = array('id' =>'GB-HRT', 'name' =>'Hertfordshire');
$options[] = array('id' =>'GB-KEN', 'name' =>'Kent');
$options[] = array('id' =>'GB-LAN', 'name' =>'Lancashire');
$options[] = array('id' =>'GB-LEC', 'name' =>'Leicestershire');
$options[] = array('id' =>'GB-LIN', 'name' =>'Lincolnshire');
$options[] = array('id' =>'GB-NFK', 'name' =>'Norfolk');
$options[] = array('id' =>'GB-NYK', 'name' =>'North Yorkshire');
$options[] = array('id' =>'GB-NTH', 'name' =>'Northamptonshire');
$options[] = array('id' =>'GB-NTT', 'name' =>'Nottinghamshire');
$options[] = array('id' =>'GB-OXF', 'name' =>'Oxfordshire');
$options[] = array('id' =>'GB-SOM', 'name' =>'Somerset');
$options[] = array('id' =>'GB-STS', 'name' =>'Staffordshire');
$options[] = array('id' =>'GB-SFK', 'name' =>'Suffolk');
$options[] = array('id' =>'GB-SRY', 'name' =>'Surrey');
$options[] = array('id' =>'GB-WAR', 'name' =>'Warwickshire');
$options[] = array('id' =>'GB-WSX', 'name' =>'West Sussex');
$options[] = array('id' =>'GB-WOR', 'name' =>'Worcestershire');
$options[] = array('id' =>'--', 'name' =>'--LONDON BOROUGHS--');
$options[] = array('id' =>'GB-BDG', 'name' =>'Barking and Dagenham');
$options[] = array('id' =>'GB-BNE', 'name' =>'Barnet');
$options[] = array('id' =>'GB-BEX', 'name' =>'Bexley');
$options[] = array('id' =>'GB-BEN', 'name' =>'Brent');
$options[] = array('id' =>'GB-BRY', 'name' =>'Bromley');
$options[] = array('id' =>'GB-CMD', 'name' =>'Camden');
$options[] = array('id' =>'GB-CRY', 'name' =>'Croydon');
$options[] = array('id' =>'GB-EAL', 'name' =>'Ealing');
$options[] = array('id' =>'GB-ENF', 'name' =>'Enfield');
$options[] = array('id' =>'GB-GRE', 'name' =>'Greenwich');
$options[] = array('id' =>'GB-HCK', 'name' =>'Hackney');
$options[] = array('id' =>'GB-HMF', 'name' =>'Hammersmith and Fulham');
$options[] = array('id' =>'GB-HRY', 'name' =>'Haringey');
$options[] = array('id' =>'GB-HRW', 'name' =>'Harrow');
$options[] = array('id' =>'GB-HAV', 'name' =>'Havering');
$options[] = array('id' =>'GB-HIL', 'name' =>'Hillingdon');
$options[] = array('id' =>'GB-HNS', 'name' =>'Hounslow');
$options[] = array('id' =>'GB-ISL', 'name' =>'Islington');
$options[] = array('id' =>'GB-KEC', 'name' =>'Kensington and Chelsea');
$options[] = array('id' =>'GB-KTT', 'name' =>'Kingston upon Thames');
$options[] = array('id' =>'GB-LBH', 'name' =>'Lambeth');
$options[] = array('id' =>'GB-LEW', 'name' =>'Lewisham');
$options[] = array('id' =>'GB-MRT', 'name' =>'Merton');
$options[] = array('id' =>'GB-NWM', 'name' =>'Newham');
$options[] = array('id' =>'GB-RDB', 'name' =>'Redbridge');
$options[] = array('id' =>'GB-RIC', 'name' =>'Richmond upon Thames');
$options[] = array('id' =>'GB-SWK', 'name' =>'Southwark');
$options[] = array('id' =>'GB-STN', 'name' =>'Sutton');
$options[] = array('id' =>'GB-TWH', 'name' =>'Tower Hamlets');
$options[] = array('id' =>'GB-WFT', 'name' =>'Waltham Forest');
$options[] = array('id' =>'GB-WND', 'name' =>'Wandsworth');
$options[] = array('id' =>'GB-WSM', 'name' =>'Westminster');
$options[] = array('id' =>'---', 'name' =>'--METRO DISTRICTS ENG--');
$options[] = array('id' =>'GB-BNS', 'name' =>'Barnsley');
$options[] = array('id' =>'GB-BIR', 'name' =>'Birmingham');
$options[] = array('id' =>'GB-BOL', 'name' =>'Bolton');
$options[] = array('id' =>'GB-BRD', 'name' =>'Bradford');
$options[] = array('id' =>'GB-BUR', 'name' =>'Bury');
$options[] = array('id' =>'GB-CLD', 'name' =>'Calderdale');
$options[] = array('id' =>'GB-COV', 'name' =>'Coventry');
$options[] = array('id' =>'GB-DNC', 'name' =>'Doncaster');
$options[] = array('id' =>'GB-DUD', 'name' =>'Dudley');
$options[] = array('id' =>'GB-GAT', 'name' =>'Gateshead');
$options[] = array('id' =>'GB-KIR', 'name' =>'Kirklees');
$options[] = array('id' =>'GB-KWL', 'name' =>'Knowsley');
$options[] = array('id' =>'GB-LDS', 'name' =>'Leeds');
$options[] = array('id' =>'GB-LIV', 'name' =>'Liverpool');
$options[] = array('id' =>'GB-MAN', 'name' =>'Manchester');
$options[] = array('id' =>'GB-NET', 'name' =>'Newcastle upon Tyne');
$options[] = array('id' =>'GB-NTY', 'name' =>'North Tyneside');
$options[] = array('id' =>'GB-OLD', 'name' =>'Oldham');
$options[] = array('id' =>'GB-RCH', 'name' =>'Rochdale');
$options[] = array('id' =>'GB-ROT', 'name' =>'Rotherham');
$options[] = array('id' =>'GB-SHN', 'name' =>'Saint Helens');
$options[] = array('id' =>'GB-SLF', 'name' =>'Salford');
$options[] = array('id' =>'GB-SAW', 'name' =>'Sandwell');
$options[] = array('id' =>'GB-SFT', 'name' =>'Sefton');
$options[] = array('id' =>'GB-SHF', 'name' =>'Sheffield');
$options[] = array('id' =>'GB-SOL', 'name' =>'Solihull');
$options[] = array('id' =>'GB-STY', 'name' =>'South Tyneside');
$options[] = array('id' =>'GB-SKP', 'name' =>'Stockport');
$options[] = array('id' =>'GB-SND', 'name' =>'Sunderland');
$options[] = array('id' =>'GB-TAM', 'name' =>'Tameside');
$options[] = array('id' =>'GB-TRF', 'name' =>'Trafford');
$options[] = array('id' =>'GB-WKF', 'name' =>'Wakefield');
$options[] = array('id' =>'GB-WLL', 'name' =>'Walsall');
$options[] = array('id' =>'GB-WGN', 'name' =>'Wigan');
$options[] = array('id' =>'GB-WRL', 'name' =>'Wirral');
$options[] = array('id' =>'GB-WLV', 'name' =>'Wolverhampton');
$options[] = array('id' =>'----', 'name' =>'--UNITARY AUTHORITIES--');
$options[] = array('id' =>'GB-BAS', 'name' =>'Bath and North East Somerset');
$options[] = array('id' =>'GB-BBD', 'name' =>'Blackburn with Darwen');
$options[] = array('id' =>'GB-BDF', 'name' =>'Bedford');
$options[] = array('id' =>'GB-BPL', 'name' =>'Blackpool');
$options[] = array('id' =>'GB-BMH', 'name' =>'Bournemouth');
$options[] = array('id' =>'GB-BRC', 'name' =>'Bracknell Forest');
$options[] = array('id' =>'GB-BNH', 'name' =>'Brighton and Hove');
$options[] = array('id' =>'GB-BST', 'name' =>'Bristol, City of');
$options[] = array('id' =>'GB-CBF', 'name' =>'Central Bedfordshire');
$options[] = array('id' =>'GB-CHE', 'name' =>'Cheshire East');
$options[] = array('id' =>'GB-CHW', 'name' =>'Cheshire West and Chester');
$options[] = array('id' =>'GB-CON', 'name' =>'Cornwall');
$options[] = array('id' =>'GB-DAL', 'name' =>'Darlington');
$options[] = array('id' =>'GB-DER', 'name' =>'Derby');
$options[] = array('id' =>'GB-DUR', 'name' =>'Durham');
$options[] = array('id' =>'GB-ERY', 'name' =>'East Riding of Yorkshire');
$options[] = array('id' =>'GB-HAL', 'name' =>'Halton');
$options[] = array('id' =>'GB-HPL', 'name' =>'Hartlepool');
$options[] = array('id' =>'GB-HEF', 'name' =>'Herefordshire');
$options[] = array('id' =>'GB-IOW', 'name' =>'Isle of Wight');
$options[] = array('id' =>'GB-KHL', 'name' =>'Kingston upon Hull');
$options[] = array('id' =>'GB-LCE', 'name' =>'Leicester');
$options[] = array('id' =>'GB-LUT', 'name' =>'Luton');
$options[] = array('id' =>'GB-MDW', 'name' =>'Medway');
$options[] = array('id' =>'GB-MDB', 'name' =>'Middlesbrough');
$options[] = array('id' =>'GB-MIK', 'name' =>'Milton Keynes');
$options[] = array('id' =>'GB-NEL', 'name' =>'North East Lincolnshire');
$options[] = array('id' =>'GB-NLN', 'name' =>'North Lincolnshire');
$options[] = array('id' =>'GB-NSM', 'name' =>'North Somerset');
$options[] = array('id' =>'GB-NBL', 'name' =>'Northumberland');
$options[] = array('id' =>'GB-NGM', 'name' =>'Nottingham');
$options[] = array('id' =>'GB-PTE', 'name' =>'Peterborough');
$options[] = array('id' =>'GB-PLY', 'name' =>'Plymouth');
$options[] = array('id' =>'GB-POL', 'name' =>'Poole');
$options[] = array('id' =>'GB-POR', 'name' =>'Portsmouth');
$options[] = array('id' =>'GB-RDG', 'name' =>'Reading');
$options[] = array('id' =>'GB-RCC', 'name' =>'Redcar and Cleveland');
$options[] = array('id' =>'GB-RUT', 'name' =>'Rutland');
$options[] = array('id' =>'GB-SHR', 'name' =>'Shropshire');
$options[] = array('id' =>'GB-SLG', 'name' =>'Slough');
$options[] = array('id' =>'GB-SGC', 'name' =>'South Gloucestershire');
$options[] = array('id' =>'GB-STH', 'name' =>'Southampton');
$options[] = array('id' =>'GB-SOS', 'name' =>'Southend-on-Sea');
$options[] = array('id' =>'GB-STT', 'name' =>'Stockton-on-Tees');
$options[] = array('id' =>'GB-STE', 'name' =>'Stoke-on-Trent');
$options[] = array('id' =>'GB-SWD', 'name' =>'Swindon');
$options[] = array('id' =>'GB-TFW', 'name' =>'Telford and Wrekin');
$options[] = array('id' =>'GB-THR', 'name' =>'Thurrock');
$options[] = array('id' =>'GB-TOB', 'name' =>'Torbay');
$options[] = array('id' =>'GB-WRT', 'name' =>'Warrington');
$options[] = array('id' =>'GB-WBK', 'name' =>'West Berkshire');
$options[] = array('id' =>'GB-WIL', 'name' =>'Wiltshire');
$options[] = array('id' =>'GB-WNM', 'name' =>'Windsor and Maidenhead');
$options[] = array('id' =>'GB-WOK', 'name' =>'Wokingham');
$options[] = array('id' =>'GB-YOR', 'name' =>'York');
$options[] = array('id' =>'GB-LND', 'name' =>'London, City of');
$options[] = array('id' =>'-----', 'name' =>'--NIR DISTRICT COUNCILS--');
$options[] = array('id' =>'GB-ANT', 'name' =>'Antrim');
$options[] = array('id' =>'GB-ARD', 'name' =>'Ards');
$options[] = array('id' =>'GB-ARM', 'name' =>'Armagh');
$options[] = array('id' =>'GB-BLA', 'name' =>'Ballymena');
$options[] = array('id' =>'GB-BLY', 'name' =>'Ballymoney');
$options[] = array('id' =>'GB-BNB', 'name' =>'Banbridge');
$options[] = array('id' =>'GB-BFS', 'name' =>'Belfast');
$options[] = array('id' =>'GB-CKF', 'name' =>'Carrickfergus');
$options[] = array('id' =>'GB-CSR', 'name' =>'Castlereagh');
$options[] = array('id' =>'GB-CLR', 'name' =>'Coleraine ');
$options[] = array('id' =>'GB-CKT', 'name' =>'Cookstown');
$options[] = array('id' =>'GB-CGV', 'name' =>'Craigavon');
$options[] = array('id' =>'GB-DRY', 'name' =>'Derry');
$options[] = array('id' =>'GB-DOW', 'name' =>'Down');
$options[] = array('id' =>'GB-DGN', 'name' =>'Dungannon');
$options[] = array('id' =>'GB-FER', 'name' =>'Fermanagh');
$options[] = array('id' =>'GB-LRN', 'name' =>'Larne');
$options[] = array('id' =>'GB-LMV', 'name' =>'Limavady');
$options[] = array('id' =>'GB-LSB', 'name' =>'Lisburn');
$options[] = array('id' =>'GB-MFT', 'name' =>'Magherafelt');
$options[] = array('id' =>'GB-MYL', 'name' =>'Moyle');
$options[] = array('id' =>'GB-NYM', 'name' =>'Newry and Mourne District');
$options[] = array('id' =>'GB-NTA', 'name' =>'Newtownabbey');
$options[] = array('id' =>'GB-NDN', 'name' =>'North Down');
$options[] = array('id' =>'GB-OMH', 'name' =>'Omagh');
$options[] = array('id' =>'GB-STB', 'name' =>'Strabane');
$options[] = array('id' =>'------', 'name' =>'--SCT COUNCIL AREAS--');
$options[] = array('id' =>'GB-ABE', 'name' =>'Aberdeen City');
$options[] = array('id' =>'GB-ABD', 'name' =>'Aberdeenshire');
$options[] = array('id' =>'GB-ANS', 'name' =>'Angus');
$options[] = array('id' =>'GB-AGB', 'name' =>'Argyll and Bute');
$options[] = array('id' =>'GB-CLK', 'name' =>'Clackmannanshire');
$options[] = array('id' =>'GB-DGY', 'name' =>'Dumfries and Galloway');
$options[] = array('id' =>'GB-DND', 'name' =>'Dundee City');
$options[] = array('id' =>'GB-EAY', 'name' =>'East Ayrshire');
$options[] = array('id' =>'GB-EDU', 'name' =>'East Dunbartonshire');
$options[] = array('id' =>'GB-ELN', 'name' =>'East Lothian');
$options[] = array('id' =>'GB-ERW', 'name' =>'East Renfrewshire');
$options[] = array('id' =>'GB-EDH', 'name' =>'Edinburgh, City');
$options[] = array('id' =>'GB-ELS', 'name' =>'Eilean Siar');
$options[] = array('id' =>'GB-FAL', 'name' =>'Falkirk');
$options[] = array('id' =>'GB-FIF', 'name' =>'Fife');
$options[] = array('id' =>'GB-GLG', 'name' =>'Glasgow City');
$options[] = array('id' =>'GB-HLD', 'name' =>'Highland');
$options[] = array('id' =>'GB-IVC', 'name' =>'Inverclyde');
$options[] = array('id' =>'GB-MLN', 'name' =>'Midlothian');
$options[] = array('id' =>'GB-MRY', 'name' =>'Moray');
$options[] = array('id' =>'GB-NAY', 'name' =>'North Ayrshire');
$options[] = array('id' =>'GB-NLK', 'name' =>'North Lanarkshire');
$options[] = array('id' =>'GB-ORK', 'name' =>'Orkney Islands');
$options[] = array('id' =>'GB-PKN', 'name' =>'Perth and Kinross');
$options[] = array('id' =>'GB-RFW', 'name' =>'Renfrewshire');
$options[] = array('id' =>'GB-SCB', 'name' =>'Scottish Borders, The');
$options[] = array('id' =>'GB-ZET', 'name' =>'Shetland Islands');
$options[] = array('id' =>'GB-SAY', 'name' =>'South Ayrshire');
$options[] = array('id' =>'GB-SLK', 'name' =>'South Lanarkshire');
$options[] = array('id' =>'GB-STG', 'name' =>'Stirling');
$options[] = array('id' =>'GB-WDU', 'name' =>'West Dunbartonshire');
$options[] = array('id' =>'GB-WLN', 'name' =>'West Lothian');
$options[] = array('id' =>'_------', 'name' =>'--WLS UNITARY AUTHORITIES--');
$options[] = array('id' =>'GB-BGW', 'name' =>'Blaenau Gwent');
$options[] = array('id' =>'GB-BGE', 'name' =>'Bridgend');
$options[] = array('id' =>'GB-CAY', 'name' =>'Caerphilly');
$options[] = array('id' =>'GB-CRF', 'name' =>'Cardiff');
$options[] = array('id' =>'GB-CMN', 'name' =>'Carmarthenshire');
$options[] = array('id' =>'GB-CGN', 'name' =>'Ceredigion');
$options[] = array('id' =>'GB-CWY', 'name' =>'Conwy');
$options[] = array('id' =>'GB-DEN', 'name' =>'Denbighshire');
$options[] = array('id' =>'GB-FLN', 'name' =>'Flintshire');
$options[] = array('id' =>'GB-GWN', 'name' =>'Gwynedd');
$options[] = array('id' =>'GB-AGY', 'name' =>'Isle of Anglesey');
$options[] = array('id' =>'GB-MTY', 'name' =>'Merthyr Tydfil');
$options[] = array('id' =>'GB-MON', 'name' =>'Monmouthshire');
$options[] = array('id' =>'GB-NTL', 'name' =>'Neath Port Talbot');
$options[] = array('id' =>'GB-NWP', 'name' =>'Newport');
$options[] = array('id' =>'GB-PEM', 'name' =>'Pembrokeshire');
$options[] = array('id' =>'GB-POW', 'name' =>'Powys');
$options[] = array('id' =>'GB-RCT', 'name' =>'Rhondda, Cynon, Taff');
$options[] = array('id' =>'GB-SWA', 'name' =>'Swansea');
$options[] = array('id' =>'GB-TOF', 'name' =>'Torfaen');
$options[] = array('id' =>'GB-VGL', 'name' =>'Vale of Glamorgan, The');
$options[] = array('id' =>'GB-WRX', 'name' =>'Wrexham');

    return $options;
}
?>